# Generated by Django 5.1.4 on 2026-07-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_emailconfirm_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirm',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
